package:
  name: adorym
  version: '1.0.0'

source:
  git_url: https://github.com/mdw771/adorym_dev.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - adorym

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
